spring:
  application:
    name: SpringProject
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  logging:
    level: error
    level.org.hibernate.SQL: DEBUG
    pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'

  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: ${SPRING_DATA_ELASTICSEARCH_CLUSTER-NODES}

  jpa:
    hibernate:
    ddl-auto: create-drop
  main:
    banner-mode: 'off'