spring:
  application:
    name: MainApplication
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/conference_finder?autoReconnect=true
    password: password
    username: root
    hikari:
        connection-timeout: 60000
        maximum-pool-size: 5

  logging:
    level: error
    level.org.hibernate.SQL: DEBUG
    pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'

  jpa:
    hibernate:
    ddl-auto: create-drop
  main:
      banner-mode: 'off'