pipeline {
    agent {
        node {
            label 'confound'
        }
    }
    stages {
        stage ('checkout git') {
            steps {
                git credentialsId: 'jenkins-gitlab', branch: 'GP19-156_deployment', url: 'git@github.com:Mendeley/grads19-be.git'
            }
        }
        stage ('ecr login') {
            steps {
                sh script:"""#!/bin/sh
                eval \$(aws ecr get-login --no-include-email --registry-ids 620835497377 --region eu-west-1)
                """
            }
        }
        stage ('docker build and push') {
            steps {
                ansiColor('xterm') {
                    sh script:"""
                    docker build -t 620835497377.dkr.ecr.eu-west-1.amazonaws.com/springbe -t 620835497377.dkr.ecr.eu-west-1.amazonaws.com/springbe:latest SpringProject/
                    docker push 620835497377.dkr.ecr.eu-west-1.amazonaws.com/springbe:latest
                    """
                }
            }
        }
        stage ('deploy') {
            steps {
                ansiColor('xterm') {
                 sh """
                    aws eks update-kubeconfig --name eks_cluster --region eu-west-1
                    kubectl set image deployment/springdeploy springbe=620835497377.dkr.ecr.eu-west-1.amazonaws.com/springbe:latest
                 """
                }
            }
        }
    }
}