apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springdeploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: confound
    spec:
      containers:
        - name: springbe
          image: 620835497377.dkr.ecr.eu-west-1.amazonaws.com/springbe:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"
          envFrom:
            - configMapRef:
                name: env-vars
          ports:
            - containerPort: 8080