#Common properties
spring:
  profiles:
    active: dev
  datasource:
    jdbcUrl: jdbc:h2:mem:memodb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  batch:
    initialize-schema: ALWAYS
    chunk-size: 1000

logging:
  level:
    root: INFO
    org:
      hibernate: INFO
      springframework:
        web: INFO

---

spring:
  profiles: dev

mysql:
  datasource:
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/conference_finder?autoReconnect=true&useSSL=false
    username: root
    password: password

elastic-search:
  endpoint: localhost
  protocol: http
  port: 9200